### ISSUE TITLE
After edit apllication settings metafields coulndn't be loaded

### ISSUE THREAD

**Issue by Kyniu** [dreamcommerce/shop-appstore-lib#6] opened 2016-01-15 14:18 UTC
In situation when I'm changing some settings in my application appearance and I accept updates in admin panel, metafields in snippets are being remove. I have to reinstall this application to fix it. It is some kind of bug?

**Comment by deallas** [comment] 2016-01-18 11:46
This is not a bug. We removed earlier all metafields when we fixed issue #5

**Comment by Kyniu** [comment] 2016-01-18 15:05
I don't think so. This is step by step instruction to reproduce "the bug":

1. On freshly installed application, metafields have correct values. Also, metafield values are correctly displayed/parsed in shop's snippets.
1. On https://panel.shoper.pl I'm editing app settings (changing html/js snippets with {metafields})
1. I'm updating application in my dev-shop
1. Now I can get correct metafields values by API but snippets won't parse/display any {metafields}. I have empty values for any metafield values in snippets.

**Comment by kusmierz** [comment] 2016-01-19 23:04
If you need any additional info about it, just contact us directly.

**Comment by deallas** [comment] 2016-02-01 13:46
Fixed in version 5.7.6

**Closed** 2016-03-09 12:26 UTC
